#!/bin/bash

# ${1} - file
# ${2} - file extension (bash or bats)
function add_shell_directive
{
  grep -q "^#!.*\b${ext}\b" "${1}"
  local -i stat=${?}
  if [[ 0 -eq ${stat} ]]
  then
    sed -i "0,/^#!.*\b${ext}\b/ s/^#!.*\b${ext}\b/&\n${SHELL/XXXX/${ext}}\n/" "${1}"
  else
    sed -i "1i${SHELL/XXXX/${ext}}\n" "${1}"
  fi
  stat=${?}
  return "${stat}"
}

function process_files
{
  local cum_stat=0
  local stat=0
  local -i lines=0
  while IFS= read -r file && [[ -n "${file}" ]]
  do
    if [[ ! -s "${file}" ]]
    then
      continue
    fi
    lines=$(wc -l "${file}" | cut -d' ' -f1)
    if [[ ${lines} -le 1 ]]
    then
      continue
    fi
    grep -q '^# \+shellcheck \+shell=' "${file}"
    if [[ 0 -eq ${?} ]]
    then
      continue
    fi
    base="$(basename "${file}")"
    ext="${base##*.}"
    if [[ -n "${ext}" ]]
    then
      add_shell_directive "${file}" "${ext}"
      stat=${?}
      if [[ 0 -ne ${stat} ]]
      then
        cum_stat=1
      fi
    fi
  done < <(find ../test -type f \( -name "*\.bats" -o -name "*\.bash" \))
  return "${cum_stat}"
}

################################################################################
# "main"                                                                       #
################################################################################
declare -r SHELL='# shellcheck shell=XXXX'
process_files

