#!/bin/bash

declare -r SCRIPT=${0##*/}

function set_color_variables
{
  if [[ -v SET_COLOR_VARIABLES ]]
  then
    return 0
  fi
  declare -rg SET_COLOR_VARIABLES=1

  if [[ -t 1 ]]
  then
    if [[ ! -v ESCAPE ]]
    then
      declare -rg ESCAPE=""
    fi
    if [[ ! -v STOP_COLOR ]]
    then
      declare -rg STOP_COLOR="${ESCAPE}[0m"
    fi
    if [[ ! -v RED ]]
    then
      declare -rg RED="${ESCAPE}[0;31m"
    fi
    if [[ ! -v YELLOW ]]
    then
      declare -rg YELLOW="${ESCAPE}[1;33m"
    fi
    if [[ ! -v GREEN ]]
    then
      declare -rg GREEN="${ESCAPE}[0;32m"
    fi
  fi

################################################################################
# In case we are running under git-bash.                                       #
################################################################################
  if [[ ! -v HOME && -v USERPROFILE ]]
  then
    local home="${USERPROFILE//\\//}"
    local drive="${home:0:1}"
    drive="${drive,,}"
    home="${drive}${home:2}"
    home=${home:-UNSET}
    export HOME="/${home}"
  fi
  export USER="${USER:-$(basename "${HOME}")}"
  return 0
}

# ${1} - message
# ${2} - message level
# ${3} - line number (optional)
function log_message
{
  set_color_variables
  local message_level=${2}
  case ${2} in
    ERROR   ) message_level=${RED}${message_level}${STOP_COLOR};;
    WARNING ) message_level=${YELLOW}${message_level}${STOP_COLOR};;
    INFO    ) message_level=${GREEN}${message_level}${STOP_COLOR};;
    *       ) :;;
  esac

################################################################################
# NOTE: Want to replace the value of the HOME environment variable with the    #
#       literal string '${HOME}' in the message.                               #
################################################################################
  local stack="${SCRIPT}"
  local message="${message_level}: ${1//${HOME}/\$\{HOME\}}"
  message="${message//${USER}/\$\{USER\}}"
  if [[ -n "${3}" ]]
  then
    message="Line = [${3}] ${message}"
  fi

  local -i index
  for ((index = $((${#FUNCNAME[@]} - 1)); index >= 0; index--))
  do
    if [[ 0 -eq ${index} ]]
    then
      break
    fi
    case ${FUNCNAME[${index}]} in
      log_info | log_warning | log_error | log_message ) break;;
      *                                                ) stack+="::${BASH_LINENO[${index}]}->${FUNCNAME[${index}]}";;
    esac
  done
  stack="[${stack}] "
  echo "${stack}${message}"
  return 0
}

# ${1} - error message
# ${2} - line number (optional)
function log_error
{
  log_message "${1}" ERROR "${2}"
  return 0
}

# ${1} - error message
# ${2} - line number (optional)
# NOTE: Let in for possible future use.
# shellcheck disable=SC2317
function log_error_no_stack
{
  set_color_variables
  echo "${RED}ERROR${STOP_COLOR}: ${2:+Line = [${2}] }${1}"
  return 0
}

# ${1} - warning message
# ${2} - line number (optional)
function log_warning
{
  log_message "${1}" WARNING "${2}"
  return 0
}

# ${1} - warning message
# ${2} - line number (optional)
# NOTE: Let in for possible future use.
# shellcheck disable=SC2317
function log_warning_no_stack
{
  set_color_variables
  echo "${YELLOW}WARNING${STOP_COLOR}: ${2:+Line = [${2}] }${1}"
  return 0
}

# ${1} - info message
# ${2} - line number (optional)
# NOTE: Let in for possible future use.
# shellcheck disable=SC2317
function log_info
{
  log_message "${1}" INFO "${2}"
  return 0
}

# ${1} - info message
# ${2} - line number (optional)
function log_info_no_stack
{
  set_color_variables
  echo "${GREEN}INFO${STOP_COLOR}: ${2:+Line = [${2}] }${1}"
  return 0
}

function get_newest_commits
{
  pushd "${PWD}" > /dev/null
  cd "${BATS_FORKS}"
  local user=$(git config --get user.name 2> /dev/null)
  user=${user//\./\\.}
  popd > /dev/null
  pretty_format="%H -%an"
  declare -Ag LOCAL_BATS_NEWEST_COMMIT
  local key
  for key in "${!BATS_FORK_SOURCE_URLS[@]}"
  do
    if [[ "bats" == "${key}" ]]
    then
      continue
    fi
    pushd "${PWD}" > /dev/null
    cd "${BATS_LOCAL_REPOS[${key}]}"
    LOCAL_BATS_NEWEST_COMMIT[${key}]="$(git log --pretty=format:"${pretty_format}" 2> /dev/null | grep -Ev "( -${user}$|${USER})" | head -1 | sed 's/ -.*$//')"
    popd > /dev/null
  done
}

# ${1} - associative array
# ${2} - label (optional)
# NOTE: Not currently used; left in for possible future use.
# shellcheck disable=SC2317
function print_array
{
  local -r label=${2:-${1}}
  local -n array=${1}
  echo "${label} size = [${#array[@]}]"
  local key=""
  for key in "${!array[@]}"
  do
    echo "${label}[${key}] = ${array[${key}]}"
  done | sort | column -s"=" -o"=" -t | sed 's/= /= [/;s/$/]/'
}

# ${1} - repository key
function show_update_steps
{
  local -r default_branch="${BATS_FORK_DEFAULT_BRANCH[${1}]}"
  echo "  To update [${1}]:"
  local dir="$(dirname "${PWD/${HOME}/\$\{HOME\}}")"
  if [[ "bats-core" != "${1}" ]]
  then
    dir+="/${1}"
  fi
##  echo "    cd ${dir}"
##  echo "    git fetch upstream --tags --force"
##  git fetch origin --force "+refs/tags/*:refs/tags/*"
##  echo "    git checkout ${default_branch}"
##  echo "    git merge upstream/${default_branch}"
##  echo "    cd -"
  echo "    cd ${dir}; git fetch upstream --tags --force; git checkout ${default_branch}; git merge upstream/${default_branch}; cd -"
  echo ''
}

function compare_newest_commits
{
  local -i stat=0
  local key
  for key in "${!LOCAL_BATS_NEWEST_COMMIT[@]}"
  do
    if [[ "${LOCAL_BATS_NEWEST_COMMIT[${key}]}" != "${BATS_FORK_SOURCE_NEWEST_COMMIT[${key}]}" ]]
    then
      log_warning "For local repository [${BATS_LOCAL_REPOS[${key}]}] newest commit [${LOCAL_BATS_NEWEST_COMMIT[${key}]}] does not match original repository newest commit [${BATS_FORK_SOURCE_NEWEST_COMMIT[${key}]}]; original repository url = [${BATS_FORK_SOURCE_URLS[${key}]}]." "${LINENO}"
      show_update_steps "${key}"
      if [[ 0 -eq ${stat} ]]
      then
        stat=1
      fi
    fi
  done
  if [[ 0 -eq ${stat} ]]
  then
    log_info_no_stack "All local BATS forks newest commits match original BATS repository newest commits."
  fi
  return "${stat}"
}

function set_variables
{
################################################################################
# The bats-core fork location. All BATS libraries are assumed to be submodules #
# in ${BATS_FORKS}.                                                            #
################################################################################
  declare -rg BATS_FORKS=${HOME}/git/bats-core

  declare -Ag BATS_FORK_SOURCE_URLS
  BATS_FORK_SOURCE_URLS[bats-core]="https://github.com/bats-core/bats-core"
  BATS_FORK_SOURCE_URLS[bats-assert]="https://github.com/bats-core/bats-assert"
  BATS_FORK_SOURCE_URLS[bats-file]="https://github.com/bats-core/bats-file"
  BATS_FORK_SOURCE_URLS[bats-support]="https://github.com/bats-core/bats-support"
  BATS_FORK_SOURCE_URLS[bats-mock]="https://github.com/jasonkarns/bats-mock"
  BATS_FORK_SOURCE_URLS[bats-mock-grayhemp]="https://github.com/grayhemp/bats-mock"

  declare -Ag BATS_FORK_DEFAULT_BRANCH
  declare -Ag BATS_FORK_SOURCE_NEWEST_COMMIT

  declare -Ag BATS_LOCAL_REPOS
  local key
  for key in "${!BATS_FORK_SOURCE_URLS[@]}"
  do
    if [[ "bats-core" == "${key}" ]]
    then
      BATS_LOCAL_REPOS[${key}]="${BATS_FORKS}"
    else
      BATS_LOCAL_REPOS[${key}]="${BATS_FORKS}/${key}"
    fi
################################################################################
# Looking for either a main branch or a master branch in the remote repository.#
################################################################################
    BATS_FORK_DEFAULT_BRANCH[${key}]="$(git ls-remote --symref "${BATS_FORK_SOURCE_URLS[${key}]}" | head -1 | sed 's@^ref: @@;s@\t.*$@@;s@^.*/@@')"
################################################################################
# Getting the most recent commit from the remote fork source repository for    #
# its default branch.                                                          #
################################################################################
    BATS_FORK_SOURCE_NEWEST_COMMIT[${key}]="$(git ls-remote "${BATS_FORK_SOURCE_URLS[${key}]}" "${BATS_FORK_DEFAULT_BRANCH[${key}]}" 2> /dev/null |  sed 's/[ \t].*$//')"
    if [[ -z "${BATS_FORK_SOURCE_NEWEST_COMMIT[${key}]}" ]]
    then
      log_error "Could not fetch the most recent default branch [${BATS_FORK_DEFAULT_BRANCH[${key}]}] commit for repository [${BATS_FORK_SOURCE_URLS[${key}]}]." "${LINENO}"
    fi
  done

################################################################################
# Original BATS project (now set as read-only).                                #
################################################################################
##  BATS_FORK_SOURCE_URLS[bats]="https://github.com/sstephenson/bats"

  return 0
}

function perform_commit_comparisons
{
  local -i stat=0
  set_variables
  stat=${?}
  if [[ 0 -ne ${stat} ]]
  then
    return "${stat}"
  fi

  get_newest_commits
  stat=${?}
  if [[ 0 -ne ${stat} ]]
  then
    return "${stat}"
  fi

  compare_newest_commits
  stat=${?}
  return "${stat}"
}

# NOTE: Not currently used; left in for possible future use.
# shellcheck disable=SC2317
function print_arrays
{
  print_array BATS_FORK_SOURCE_URLS
  echo ''
  print_array BATS_FORK_SOURCE_NEWEST_COMMIT
  echo ''
  print_array BATS_FORK_DEFAULT_BRANCH
  echo ''
  print_array LOCAL_BATS_NEWEST_COMMIT
  echo ''
}

################################################################################
# "main"                                                                       #
################################################################################
set_color_variables
perform_commit_comparisons
exit "${?}"

