#!/bin/bash

declare -r SCRIPT=${0##*/}

# ${1} - message
# ${2} - message level
# ${3} - line number (optional)
function log_message
{
  if [[ ! -v ESCAPE ]]
  then
    declare -rg ESCAPE=""
  fi

  if [[ ! -v STOP_COLOR ]]
  then
    local -r STOP_COLOR="${ESCAPE}[0m"
  fi

  local message_level=${2}
  if [[ -t 1 ]]
  then
    case ${2} in
      ERROR   ) if [[ ! -v RED ]]
                then
                  declare -rg RED="${ESCAPE}[0;31m"
                fi
                message_level=${RED}${message_level}${STOP_COLOR};;
      WARNING ) if [[ ! -v YELLOW ]]
                then
                  declare -rg YELLOW="${ESCAPE}[1;33m"
                fi
                message_level=${YELLOW}${message_level}${STOP_COLOR};;
      INFO    ) if [[ ! -v GREEN ]]
                then
                  declare -rg GREEN="${ESCAPE}[0;32m"
                fi
                message_level=${GREEN}${message_level}${STOP_COLOR};;
      *       ) :;;
    esac
  fi

################################################################################
# NOTE: Want to replace the value of the HOME environment variable with the    #
#       literal string '${HOME}' in the message.                               #
################################################################################
  local stack="${SCRIPT}"
  local message="${message_level}: ${1//${HOME}/\$\{HOME\}}"
  message="${message//${USER}/\$\{USER\}}"
  if [[ -n "${3}" ]]
  then
    message="Line = [${3}] ${message}"
  fi

  local -i index
  for ((index = $((${#FUNCNAME[@]} - 1)); index >= 0; index--))
  do
    if [[ 0 -eq ${index} ]]
    then
      break
    fi
    case ${FUNCNAME[${index}]} in
      log_info | log_warning | log_error | log_message ) break;;
      *                                                ) stack+="::${BASH_LINENO[${index}]}->${FUNCNAME[${index}]}";;
    esac
  done
  stack="[${stack}] "
  echo "${stack}${message}"
  return 0
}

# ${1} - error message
# ${2} - line number (optional)
function log_error
{
  log_message "${1}" ERROR "${2}"
  return 0
}

# ${1} - warning message
# ${2} - line number (optional)
function log_warning
{
  log_message "${1}" WARNING "${2}"
  return 0
}

# ${1} - info message
# ${2} - line number (optional)
function log_info
{
  log_message "${1}" INFO "${2}"
  return 0
}

################################################################################
# PURPOSE:                                                                     #
# Print script usage information.                                              #
#                                                                              #
# INPUT VARIABLES:                                                             #
# ${1} - the exit code                                                         #
#                                                                              #
# OUTPUT:                                                                      #
# Usage information to stdout will be printed and then this                    #
# script will exit with a status of ${1}.                                      #
################################################################################
function usage
{
  local bats_libs="$(echo "${!BATS_CORE_LIB_REPOS[@]}" | tr ' ' '\n' | sort | tr '\n' ' ' | sed 's/ $//')"
  cat << EOF
  Clones the bats-core repository and the bats-core libraries
    {${bats_libs// /, }}
  into a specified directory.
  Usage: ${SCRIPT} -d,--dir [directory] -h,--help
  -d,--dir  Specifies the directory into which the bats-core repository will
            be cloned. If the directory does not exist, it will be created.
            Required.
  -n,--name Specifies the local bats-core directory name. Default value is [${BATS_CORE_DEFAULT_LOCAL_NAME}].
            Optional.
  -h,--help Prints this usage information and exits. Takes precedence over all
            other options. Optional.
EOF
  exit "${1}"
}

################################################################################
# PURPOSE:                                                                     #
# Parses this script's command line options.                                   #
#                                                                              #
# ARGUMENTS:                                                                   #
# ${@} - this script's command line                                            #
################################################################################
function parse_command_line_options
{
################################################################################
# Setting the long versions of the command line options.                       #
# NOTE: An option followed by a ':' means the option takes a required          #
#       argument.                                                              #
#       An option followed by a "::" means the option takes an optional        #
#       argument (for such an argument use "shift 2" instead of "shift 1" in   #
#       the getopt while loop).                                                #
################################################################################
  local long_options="dir:,name:,help"

################################################################################
# To get the short options that correspond to the long options, we basically   #
# just get the first letter of each long option.                               #
#                                                                              #
# NOTE: If more than one long option begins with the same letter, then you     #
#       must:                                                                  #
#         - only assign one of these long options to long_options              #
#         - extract the short options from long_options as usual               #
#         - manually assign the remaining long options to long_options and     #
#           update short_options as appropriate                                #
################################################################################
  local short_options=$(echo "${long_options}" | tr ',' '\n' | sed 's/\(^.\)\(.*[^:]\)\(:\{0,2\}$\)/\1\3/' | tr -d '\n')

################################################################################
# --longoptions → specifies long options                                       #
# --alternative → allow long options to start with a single dash ('-') instead #
#                 of restricting long options to only "--"                     #
# --name        → program name to use for error messages                       #
# --options     → specifies short options                                      #
# --quiet       → disable error reporting (we will perform our own error       #
#                 reporting)                                                   #
# :             → exactly one required argument for the option                 #
# ::            → exactly one optional argument for the option                 #
#                 NOTE: Must use like: -o23 OR --option=23                     #
#                                                                              #
# NOTE: Options present on the command line but not specified in opts will not #
#       end up in opts.                                                        #
################################################################################
  opts=$(getopt --alternative --name "${SCRIPT}" --options "${short_options}" --longoptions "${long_options}" -- "${@}")
  if [[ ${?} != 0 ]]
  then
    log_error "Could not parse the command line option(s) [${*}]. Exiting." "${LINENO}"
    usage 1
  fi

################################################################################
# Preserves white space in opts.                                               #
################################################################################
  eval set -- "${opts}"

  BATS_CORE_LOCAL_NAME="${BATS_CORE_DEFAULT_LOCAL_NAME}"
  while [[ true ]]
  do
    case ${1} in
      -d | --dir  ) declare -rg REPOS_DIR="${2}"
                    shift 2;;

      -n | --name ) declare -rg BATS_CORE_LOCAL_NAME="${2}"
                    shift 2;;

      -h | --help ) usage 0;;

################################################################################
# End of opts marker is "--".                                                  #
################################################################################
      --          ) shift 1
                    break;;

      *           ) log_error "Unknown internal [getopt] error. Exiting." "${LINENO}"
                    usage 1;;
    esac
  done

  if [[ ! -v REPOS_DIR ]]
  then
    log_error "Must specify a directory for the bats-core repository and libraries. Exiting." "${LINENO}"
    exit 1
  fi
}

# ${1} - submodule git repository url
# ${2} - full path to submodule destination directory
function add_submodule
{
  pushd "${PWD}" > /dev/null
  local -r sub_parent_dir="$(dirname "${2}")"
  cd "${sub_parent_dir}"
  local -r sub_dir="$(basename "${2}")"
  git submodule add -b "${BATS_DEFAULT_BRANCHES[${sub_dir}]}" "${1}" "${sub_dir}" > /dev/null 2>&1
  local -i stat=${?}
  if [[ 0 -eq ${stat} ]]
  then
    log_info "Added submodule [${1}], branch [${BATS_DEFAULT_BRANCHES[${sub_dir}]}], to [${sub_parent_dir}]." "${LINENO}"
    BATS_CORE_ADDED_SUBMODULES+=" ${sub_dir}"
    echo ''
  else
    log_error "Failed to add submodule [${1}], branch [${BATS_DEFAULT_BRANCHES[${sub_dir}]:-UNKNOWN}], to [${2}] due to error code [${stat}]. Exiting." "${LINENO}"
    exit 1
  fi
  popd > /dev/null
}

function clone_bats_core_repos
{
  local -i stat=0
  if [[ ! -d "${REPOS_DIR}" ]]
  then
    mkdir -p "${REPOS_DIR}"
    stat=${?}
    if [[ 0 -ne ${stat} ]]
    then
      log_error "Failed to create new directory [${REPOS_DIR}] due to error code [${stat}]. Exiting." "${LINENO}"
      exit 1
    fi
  fi

  local -r bats_core_repo="${REPOS_DIR}/${BATS_CORE_LOCAL_NAME}"
  if [[ -d "${bats_core_repo}" ]]
  then
    log_error "The bats-core repository [${bats_core_repo}] already exists; it will not be over written. Exiting." "${LINENO}"
    exit 1
  fi

  git clone -b "${BATS_DEFAULT_BRANCHES[${BATS_CORE}]}" "${BATS_CORE_URL}" "${bats_core_repo}" > /dev/null 2>&1
  stat=${?}
  if [[ 0 -eq ${stat} ]]
  then
    log_info "Cloned [${BATS_CORE_URL}], branch [${BATS_DEFAULT_BRANCHES[${BATS_CORE}]}], into [${bats_core_repo}]." "${LINENO}"
    pushd "${PWD}" > /dev/null
    cd "${bats_core_repo}"
    git checkout -b "${BATS_CORE_LIBS_BRANCH}" > /dev/null 2>&1
    stat=${?}
    if [[ 0 -eq ${stat} ]]
    then
      log_info "Created new branch [${BATS_CORE_LIBS_BRANCH}] in repository [${bats_core_repo}]." "${LINENO}"
    else
      log_error "Failed to create new branch [${BATS_CORE_LIBS_BRANCH}] in repository [${bats_core_repo}] due to error code [${stat}]. Exiting." "${LINENO}"
      exit 1
    fi
    popd > /dev/null
    echo ''
  else
    log_error "Failed to clone [${BATS_CORE_URL}], branch [${BATS_DEFAULT_BRANCHES[${BATS_CORE}]}], into [${bats_core_repo}] due to error code [${stat}]. Exiting." "${LINENO}"
    exit 1
  fi

  local key
  for key in $(echo "${!BATS_CORE_LIB_REPOS[@]}" | tr ' ' '\n' | sort)
  do
    add_submodule "${BATS_CORE_LIB_REPOS[${key}]}" "${bats_core_repo}/${key}"
  done

  if [[ -n "${BATS_CORE_ADDED_SUBMODULES}" ]]
  then
    BATS_CORE_ADDED_SUBMODULES="${BATS_CORE_ADDED_SUBMODULES# }"
    pushd "${PWD}" > /dev/null
    cd "${bats_core_repo}"
    git commit -m "Added submodules {${BATS_CORE_ADDED_SUBMODULES// /, }}." > /dev/null
################################################################################
# Deleting sample hook files.                                                  #
################################################################################
    find .git -path "*/hooks/*" -type f -name "*\.sample" -delete
    popd > /dev/null
  fi
}

# ${1} - BATS_DEFAULT_BRANCHES array key
# ${2} - BATS repositlry url
function add_default_branch
{
  BATS_DEFAULT_BRANCHES[${1}]="$(git ls-remote --symref "${2}" | head -1 | sed 's@^ref: @@;s@\t.*$@@;s@^.*/@@')"
}

function set_variables
{
  declare -rg BATS_CORE_URL="https://github.com/bats-core/bats-core"
  local bats_core="$(basename "${BATS_CORE_URL}")"
  declare -rg BATS_CORE=${bats_core%.git}

  declare -Ag BATS_CORE_LIB_REPOS
  BATS_CORE_LIB_REPOS[bats-assert]="https://github.com/bats-core/bats-assert"
  BATS_CORE_LIB_REPOS[bats-file]="https://github.com/bats-core/bats-file"
  BATS_CORE_LIB_REPOS[bats-mock-grayhemp]="https://github.com/grayhemp/bats-mock"
  BATS_CORE_LIB_REPOS[bats-mock]="https://github.com/jasonkarns/bats-mock"
  BATS_CORE_LIB_REPOS[bats-support]="https://github.com/bats-core/bats-support"

  declare -Ag BATS_DEFAULT_BRANCHES
  local key
  for key in "${!BATS_CORE_LIB_REPOS[@]}" ${BATS_CORE}
  do
################################################################################
# Looking for either a main branch or a master branch in the remote repository.#
################################################################################
    case "${key}" in
      "${BATS_CORE}" ) add_default_branch "${BATS_CORE}" "${BATS_CORE_URL}";;
      *              ) add_default_branch "${key}" "${BATS_CORE_LIB_REPOS[${key}]}";;
    esac
  done

  declare -g BATS_CORE_ADDED_SUBMODULES
  declare -rg BATS_CORE_DEFAULT_LOCAL_NAME=bats-core-original
  declare -rg BATS_CORE_LIBS_BRANCH=bats-core-libs
}

################################################################################
# "main"                                                                       #
################################################################################
set_variables
parse_command_line_options "${@}"
clone_bats_core_repos

